// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwQvpG8pBLbpNBHUe2V5OJnFxH_5cn3MQ',
    appId: '1:460060665147:web:0498f35e8f07a4dd72431e',
    messagingSenderId: '460060665147',
    projectId: 'income-expense-efb92',
    authDomain: 'income-expense-efb92.firebaseapp.com',
    storageBucket: 'income-expense-efb92.appspot.com',
    measurementId: 'G-KNKB6FH87L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKjevnyysl8NPi21Hrspd_m7k65-KYbZY',
    appId: '1:460060665147:android:c952e0ee218a01bb72431e',
    messagingSenderId: '460060665147',
    projectId: 'income-expense-efb92',
    storageBucket: 'income-expense-efb92.appspot.com',
  );
}
